"""empty message

Revision ID: eeb470fae984
Revises: 5ab7dc9a45a4
Create Date: 2020-02-08 18:37:56.403732

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eeb470fae984'
down_revision = '5ab7dc9a45a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.add_column('users', sa.Column('metric', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'metric')
    op.drop_column('users', 'is_active')
    # ### end Alembic commands ###
